"""Summary added

Revision ID: 0002
Revises:
Create Date: 2022-10-29 18:58:54.885119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_description', table_name='items')
    op.drop_index('ix_items_id', table_name='items')
    op.drop_index('ix_items_title', table_name='items')
    op.drop_table('items')
    op.create_table('items')
    op.add_column('summaries', sa.Column('url', sa.String(), nullable=True))
    op.drop_index('ix_summaries_description', table_name='summaries')
    op.drop_index('ix_summaries_id', table_name='summaries')
    op.drop_index('ix_summaries_title', table_name='summaries')
    op.create_unique_constraint(None, 'summaries', ['url'])
    op.create_unique_constraint(None, 'summaries', ['id'])
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_constraint(None, 'summaries', type_='unique')
    op.drop_constraint(None, 'summaries', type_='unique')
    op.create_index('ix_summaries_title', 'summaries', ['title'], unique=False)
    op.create_index('ix_summaries_id', 'summaries', ['id'], unique=False)
    op.create_index('ix_summaries_description', 'summaries', ['description'], unique=False)
    op.drop_column('summaries', 'url')
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='items_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_index('ix_items_title', 'items', ['title'], unique=False)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.create_index('ix_items_description', 'items', ['description'], unique=False)
    # ### end Alembic commands ###
